languageCode: 'en-us'
title: 'BioCurious'
theme: 
- "hugo-shortcode-roneo-collection"
- "hextra"

markup:
  goldmark:
    renderer:
      unsafe: "true"


params:

  address: "3108 Patrick Henry Drive, Santa Clara, CA, 95054"
  email: "info@biocurious.org"
  #phone: "555 555 5555"

  navbar:
    # width: normal
    displayTitle: false
    displayLogo: true
    logo:
      path: 'img/biocurious-logo.png'
      link: '/biocurious-org/'
      width: 200
      height: 200

  footer:
    enabled: "true"
    displayCopyright: "true"

  theme:
    default: 'light'
    displayToggle: false

  enableGitInfo: true
  displayUpdatedDate: true
  dateFormat: "January 2, 2006"

  page:
    # width: normal

  search:
    enable: true
    type: flexsearch
    flexsearch:
      index: content

  blog:
    list:
      displayTags: true
      pagerSize: 20
    toc:
      displayTags: true

menu:
  main:

  - name: FAQ
    pageRef: "/faq/"
    weight: 10

  - name: Events
    pageRef: "/events"
    weight: 20

  - name: Projects
    identifier: projects
    pageRef: "/projects/"
    weight: 30

  # - name: Project A
  #   pageRef: "/projects/project-a"
  #   parent: projects
  # - name: Project B
  #   pageRef: "/projects/project-b"
  #   parent: projects

  - name: Blog
    pageRef: "/blog/"
    weight: 40

  #

  - name: Membership
    pageRef: "/membership"
    weight: 50

  - name: Donations
      #name: "Donate reagents and gear"
    pageRef: "/donations"
    weight: 70

  #
 

  - name: Wiki
    url: "/wiki"
    weight: 90

  - name: Search
    weight: 100
    params:
      type: search
 
