
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_FORCE_HTTPS: "true"

hugo: 
  image: "hugomods/hugo:exts"
  script:
    #- git submodule update --init --remote --merge
    - hugo --gc --baseURL "https://darachm.github.io/biocurious-org"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment: production

wiki:
  image: python:latest
  script:
    - ls
    - pwd
    - git clone https://gitlab.com/darachm/biocurious-org.wiki wiki
    - pip install zensical
    - ls
    - ls -a
    - pwd
    - zensical build 
    - find public/wiki -name '*.html' -type f -print0 | xargs -0 sed -i 's/.md"\( title="Edit this page" class="md-content__button md-icon" rel="edit"\)/?edit=true" \1/g'
    - find public/wiki -name '*.html' -type f -print0 | xargs -0 sed -i 's/.md"\( title="View source of this page" class="md-content__button md-icon"\)/" \1/g'
  artifacts:
    paths:
      - public/wiki
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/ 
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

pages-publish:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  image: python:latest
  dependencies:
    - hugo
    - wiki
  pages:
    publish: public
  script:
    - echo "hi"


